### ISSUE TITLE
Use the new location of the Tribal Leaders Directory's and remove the ID column before committing to the repo

### ISSUE THREAD

**Issue by h-m-f-t** [cisagov/flat-tribal-leaders#3]
### Issue description

Knowing when the Tribal Leaders Directory updates (and to what) remains very useful to the .gov registry. Earlier this year, BIA updated where they were updating the file. They also added a ID value to the dataset that appears to change for each record on each update ([see my fork's commits](https://github.com/h-m-f-t/flat-tribal-leaders/commits/main/)). 

Let's strip the ID, sort the data, and then commit to our repo to we can track individual changes.

### Acceptance criteria
- [ ] Fork this repo (for easier testing)
- [ ] In [flat.yml](https://github.com/cisagov/flat-tribal-leaders/blob/main/.github/workflows/flat.yml), point `http_url` at https://services1.arcgis.com/UxqqIfhng71wUT9x/arcgis/rest/services/TribalLeadership_Directory/FeatureServer/replicafilescache/TribalLeadership_Directory_-8807089639668789909.csv
- [ ] In-Action, strip the first column of data (`OBJECTID`) and sort by the new first column (`Tribe Full Name`)
- [ ] Save to tribal-leaders.csv
- [ ] PR your fork into this repo

### Additional context

The product team hasn't worked in this repo, but it's used by the program team. Check out the [README](https://github.com/cisagov/flat-tribal-leaders/).

### Links to other issues

* 🔄 Similar to https://github.com/cisagov/dotgov-data/issues/118

**Comment by abroddrick** [comment]
I can't edit this issue, but could you add this link to the [flat.yml ](https://github.com/cisagov/flat-tribal-leaders/blob/main/.github/workflows/flat.yml) text. And can you add a preface to this that "As a team we haven't developed int his repo before, please see [this readme](https://github.com/cisagov/flat-tribal-leaders?tab=readme-ov-file#flat-tribal-leaders) for a little background". Also, since there haven't been any commits to this repo in the last 5 months, I assume there is no need for the dev to fork the repo, correct? (Point wise, I think I would do a 3, as our chron job tickets seem to linger more than 2 days usually, but it should be more like 3 days to implement/test etc, not the full week hopefully.)

**Comment by h-m-f-t** [comment]
Nice! 

@Matt-Spence, are the line endings between the CSV in-repo and the one on arcgis.com different? I had anticipated being able to see line edits instead of the wholesale revision of the entire file. 

If so, it might be worth an intermediary step to commit a version that shows the diff pre-line ending change so we can at least say "ah, the BIA leader changed in the 6-month interim when our scraping was borked." Does that make sense?

**Comment by Matt-Spence** [comment]
> Nice!
> 
> @Matt-Spence, are the line endings between the CSV in-repo and the one on arcgis.com different? I had anticipated being able to see line edits instead of the wholesale revision of the entire file.
> 
> If so, it might be worth an intermediary step to commit a version that shows the diff pre-line ending change so we can at least say "ah, the BIA leader changed in the 6-month interim when our scraping was borked." Does that make sense?

Looking at the old data file I think the issue is how the two files are sorted. The old data doesn't appear to be sorted by any kind of index I can see, whereas the new data comes sorted by default by Tribe (not the full name), and I've sorted by Tribe Full Name as the ticket specified. The result is a totally different file.

**Comment by h-m-f-t** [comment]
Oh, sorry to make these comments on the issue and not the PR. That all makes sense.

I'm going to sort the file by Tribe Full Name and commit that, then we should see a diff.
